/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// AtlasConstraintDef struct for AtlasConstraintDef
type AtlasConstraintDef struct {
	Type string `json:"type,omitempty"`
	Params map[string]map[string]interface{} `json:"params,omitempty"`
}
