/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// SubjectVersion struct for SubjectVersion
type SubjectVersion struct {
	Subject string `json:"subject,omitempty"`
	Version int32 `json:"version,omitempty"`
}
