/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// ExporterStatus struct for ExporterStatus
type ExporterStatus struct {
	Name string `json:"name,omitempty"`
	State string `json:"state,omitempty"`
	Offset int64 `json:"offset,omitempty"`
	Ts int64 `json:"ts,omitempty"`
	Trace string `json:"trace,omitempty"`
}
