/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema-registry-sdk

type Schema struct {
	Subject string `json:"subject,omitempty"`
	Version int32 `json:"version,omitempty"`
	Id int32 `json:"id,omitempty"`
	Schema string `json:"schema,omitempty"`
}
