/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// SearchParams struct for SearchParams
type SearchParams struct {
	IncludeDeleted bool `json:"includeDeleted,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	Offset int32 `json:"offset,omitempty"`
}
