/*
Confluent Schema Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schemaregistry

import (
	"encoding/json"
)

import (
	"reflect"
)

// AssociationFilterConfig struct for AssociationFilterConfig
type AssociationFilterConfig struct {
	TopicsToInclude *[]string `json:"topicsToInclude,omitempty"`
	TopicsToExclude *[]string `json:"topicsToExclude,omitempty"`
	SubjectRenameFormat *string `json:"subjectRenameFormat,omitempty"`
	ContextType *string `json:"contextType,omitempty"`
	Context *string `json:"context,omitempty"`
	SourceSRDeployment *string `json:"sourceSRDeployment,omitempty"`
	SourceLSRC *string `json:"sourceLSRC,omitempty"`
	SourceSRBackingKafkaId *string `json:"sourceSRBackingKafkaId,omitempty"`
	SourceSRGroupId *string `json:"sourceSRGroupId,omitempty"`
}

// NewAssociationFilterConfig instantiates a new AssociationFilterConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssociationFilterConfig() *AssociationFilterConfig {
	this := AssociationFilterConfig{}
	return &this
}

// NewAssociationFilterConfigWithDefaults instantiates a new AssociationFilterConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssociationFilterConfigWithDefaults() *AssociationFilterConfig {
	this := AssociationFilterConfig{}
	return &this
}

// GetTopicsToInclude returns the TopicsToInclude field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetTopicsToInclude() []string {
	if o == nil || o.TopicsToInclude == nil {
		var ret []string
		return ret
	}
	return *o.TopicsToInclude
}

// GetTopicsToIncludeOk returns a tuple with the TopicsToInclude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetTopicsToIncludeOk() (*[]string, bool) {
	if o == nil || o.TopicsToInclude == nil {
		return nil, false
	}
	return o.TopicsToInclude, true
}

// HasTopicsToInclude returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasTopicsToInclude() bool {
	if o != nil && o.TopicsToInclude != nil {
		return true
	}

	return false
}

// SetTopicsToInclude gets a reference to the given []string and assigns it to the TopicsToInclude field.
func (o *AssociationFilterConfig) SetTopicsToInclude(v []string) {
	o.TopicsToInclude = &v
}

// GetTopicsToExclude returns the TopicsToExclude field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetTopicsToExclude() []string {
	if o == nil || o.TopicsToExclude == nil {
		var ret []string
		return ret
	}
	return *o.TopicsToExclude
}

// GetTopicsToExcludeOk returns a tuple with the TopicsToExclude field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetTopicsToExcludeOk() (*[]string, bool) {
	if o == nil || o.TopicsToExclude == nil {
		return nil, false
	}
	return o.TopicsToExclude, true
}

// HasTopicsToExclude returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasTopicsToExclude() bool {
	if o != nil && o.TopicsToExclude != nil {
		return true
	}

	return false
}

// SetTopicsToExclude gets a reference to the given []string and assigns it to the TopicsToExclude field.
func (o *AssociationFilterConfig) SetTopicsToExclude(v []string) {
	o.TopicsToExclude = &v
}

// GetSubjectRenameFormat returns the SubjectRenameFormat field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetSubjectRenameFormat() string {
	if o == nil || o.SubjectRenameFormat == nil {
		var ret string
		return ret
	}
	return *o.SubjectRenameFormat
}

// GetSubjectRenameFormatOk returns a tuple with the SubjectRenameFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetSubjectRenameFormatOk() (*string, bool) {
	if o == nil || o.SubjectRenameFormat == nil {
		return nil, false
	}
	return o.SubjectRenameFormat, true
}

// HasSubjectRenameFormat returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasSubjectRenameFormat() bool {
	if o != nil && o.SubjectRenameFormat != nil {
		return true
	}

	return false
}

// SetSubjectRenameFormat gets a reference to the given string and assigns it to the SubjectRenameFormat field.
func (o *AssociationFilterConfig) SetSubjectRenameFormat(v string) {
	o.SubjectRenameFormat = &v
}

// GetContextType returns the ContextType field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetContextType() string {
	if o == nil || o.ContextType == nil {
		var ret string
		return ret
	}
	return *o.ContextType
}

// GetContextTypeOk returns a tuple with the ContextType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetContextTypeOk() (*string, bool) {
	if o == nil || o.ContextType == nil {
		return nil, false
	}
	return o.ContextType, true
}

// HasContextType returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasContextType() bool {
	if o != nil && o.ContextType != nil {
		return true
	}

	return false
}

// SetContextType gets a reference to the given string and assigns it to the ContextType field.
func (o *AssociationFilterConfig) SetContextType(v string) {
	o.ContextType = &v
}

// GetContext returns the Context field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetContext() string {
	if o == nil || o.Context == nil {
		var ret string
		return ret
	}
	return *o.Context
}

// GetContextOk returns a tuple with the Context field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetContextOk() (*string, bool) {
	if o == nil || o.Context == nil {
		return nil, false
	}
	return o.Context, true
}

// HasContext returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasContext() bool {
	if o != nil && o.Context != nil {
		return true
	}

	return false
}

// SetContext gets a reference to the given string and assigns it to the Context field.
func (o *AssociationFilterConfig) SetContext(v string) {
	o.Context = &v
}

// GetSourceSRDeployment returns the SourceSRDeployment field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetSourceSRDeployment() string {
	if o == nil || o.SourceSRDeployment == nil {
		var ret string
		return ret
	}
	return *o.SourceSRDeployment
}

// GetSourceSRDeploymentOk returns a tuple with the SourceSRDeployment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetSourceSRDeploymentOk() (*string, bool) {
	if o == nil || o.SourceSRDeployment == nil {
		return nil, false
	}
	return o.SourceSRDeployment, true
}

// HasSourceSRDeployment returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasSourceSRDeployment() bool {
	if o != nil && o.SourceSRDeployment != nil {
		return true
	}

	return false
}

// SetSourceSRDeployment gets a reference to the given string and assigns it to the SourceSRDeployment field.
func (o *AssociationFilterConfig) SetSourceSRDeployment(v string) {
	o.SourceSRDeployment = &v
}

// GetSourceLSRC returns the SourceLSRC field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetSourceLSRC() string {
	if o == nil || o.SourceLSRC == nil {
		var ret string
		return ret
	}
	return *o.SourceLSRC
}

// GetSourceLSRCOk returns a tuple with the SourceLSRC field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetSourceLSRCOk() (*string, bool) {
	if o == nil || o.SourceLSRC == nil {
		return nil, false
	}
	return o.SourceLSRC, true
}

// HasSourceLSRC returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasSourceLSRC() bool {
	if o != nil && o.SourceLSRC != nil {
		return true
	}

	return false
}

// SetSourceLSRC gets a reference to the given string and assigns it to the SourceLSRC field.
func (o *AssociationFilterConfig) SetSourceLSRC(v string) {
	o.SourceLSRC = &v
}

// GetSourceSRBackingKafkaId returns the SourceSRBackingKafkaId field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetSourceSRBackingKafkaId() string {
	if o == nil || o.SourceSRBackingKafkaId == nil {
		var ret string
		return ret
	}
	return *o.SourceSRBackingKafkaId
}

// GetSourceSRBackingKafkaIdOk returns a tuple with the SourceSRBackingKafkaId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetSourceSRBackingKafkaIdOk() (*string, bool) {
	if o == nil || o.SourceSRBackingKafkaId == nil {
		return nil, false
	}
	return o.SourceSRBackingKafkaId, true
}

// HasSourceSRBackingKafkaId returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasSourceSRBackingKafkaId() bool {
	if o != nil && o.SourceSRBackingKafkaId != nil {
		return true
	}

	return false
}

// SetSourceSRBackingKafkaId gets a reference to the given string and assigns it to the SourceSRBackingKafkaId field.
func (o *AssociationFilterConfig) SetSourceSRBackingKafkaId(v string) {
	o.SourceSRBackingKafkaId = &v
}

// GetSourceSRGroupId returns the SourceSRGroupId field value if set, zero value otherwise.
func (o *AssociationFilterConfig) GetSourceSRGroupId() string {
	if o == nil || o.SourceSRGroupId == nil {
		var ret string
		return ret
	}
	return *o.SourceSRGroupId
}

// GetSourceSRGroupIdOk returns a tuple with the SourceSRGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssociationFilterConfig) GetSourceSRGroupIdOk() (*string, bool) {
	if o == nil || o.SourceSRGroupId == nil {
		return nil, false
	}
	return o.SourceSRGroupId, true
}

// HasSourceSRGroupId returns a boolean if a field has been set.
func (o *AssociationFilterConfig) HasSourceSRGroupId() bool {
	if o != nil && o.SourceSRGroupId != nil {
		return true
	}

	return false
}

// SetSourceSRGroupId gets a reference to the given string and assigns it to the SourceSRGroupId field.
func (o *AssociationFilterConfig) SetSourceSRGroupId(v string) {
	o.SourceSRGroupId = &v
}

// Redact resets all sensitive fields to their zero value.
func (o *AssociationFilterConfig) Redact() {
    o.recurseRedact(o.TopicsToInclude)
    o.recurseRedact(o.TopicsToExclude)
    o.recurseRedact(o.SubjectRenameFormat)
    o.recurseRedact(o.ContextType)
    o.recurseRedact(o.Context)
    o.recurseRedact(o.SourceSRDeployment)
    o.recurseRedact(o.SourceLSRC)
    o.recurseRedact(o.SourceSRBackingKafkaId)
    o.recurseRedact(o.SourceSRGroupId)
}

func (o *AssociationFilterConfig) recurseRedact(v interface{}) {
    type redactor interface {
        Redact()
    }
    if r, ok := v.(redactor); ok {
        r.Redact()
    } else {
        val := reflect.ValueOf(v)
        if val.Kind() == reflect.Ptr {
            val = val.Elem()
        }
        switch val.Kind() {
        case reflect.Slice, reflect.Array:
            for i := 0; i < val.Len(); i++ {
                // support data types declared without pointers
                o.recurseRedact(val.Index(i).Interface())
                // ... and data types that were declared without but need pointers (for Redact)
                if val.Index(i).CanAddr() {
                    o.recurseRedact(val.Index(i).Addr().Interface())
                }
            }
        }
    }
}

func (o AssociationFilterConfig) zeroField(v interface{}) {
    p := reflect.ValueOf(v).Elem()
    p.Set(reflect.Zero(p.Type()))
}

func (o AssociationFilterConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TopicsToInclude != nil {
		toSerialize["topicsToInclude"] = o.TopicsToInclude
	}
	if o.TopicsToExclude != nil {
		toSerialize["topicsToExclude"] = o.TopicsToExclude
	}
	if o.SubjectRenameFormat != nil {
		toSerialize["subjectRenameFormat"] = o.SubjectRenameFormat
	}
	if o.ContextType != nil {
		toSerialize["contextType"] = o.ContextType
	}
	if o.Context != nil {
		toSerialize["context"] = o.Context
	}
	if o.SourceSRDeployment != nil {
		toSerialize["sourceSRDeployment"] = o.SourceSRDeployment
	}
	if o.SourceLSRC != nil {
		toSerialize["sourceLSRC"] = o.SourceLSRC
	}
	if o.SourceSRBackingKafkaId != nil {
		toSerialize["sourceSRBackingKafkaId"] = o.SourceSRBackingKafkaId
	}
	if o.SourceSRGroupId != nil {
		toSerialize["sourceSRGroupId"] = o.SourceSRGroupId
	}
	return json.Marshal(toSerialize)
}

type NullableAssociationFilterConfig struct {
	value *AssociationFilterConfig
	isSet bool
}

func (v NullableAssociationFilterConfig) Get() *AssociationFilterConfig {
	return v.value
}

func (v *NullableAssociationFilterConfig) Set(val *AssociationFilterConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableAssociationFilterConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableAssociationFilterConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssociationFilterConfig(val *AssociationFilterConfig) *NullableAssociationFilterConfig {
	return &NullableAssociationFilterConfig{value: val, isSet: true}
}

func (v NullableAssociationFilterConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssociationFilterConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


