/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// Rule Rule
type Rule struct {
	// Rule name
	Name string `json:"name,omitempty"`
	// Rule doc
	Doc string `json:"doc,omitempty"`
	// Rule kind
	Kind string `json:"kind,omitempty"`
	// Rule mode
	Mode string `json:"mode,omitempty"`
	// Rule type
	Type string `json:"type,omitempty"`
	// The tags to which this rule applies
	Tags []string `json:"tags,omitempty"`
	// Optional params for the rule
	Params map[string]string `json:"params,omitempty"`
	// Rule expression
	Expr string `json:"expr,omitempty"`
	// Rule action on success
	OnSuccess string `json:"onSuccess,omitempty"`
	// Rule action on failure
	OnFailure string `json:"onFailure,omitempty"`
	// Whether the rule is disabled
	Disabled bool `json:"disabled,omitempty"`
}
