/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// AtlasEntity struct for AtlasEntity
type AtlasEntity struct {
	TypeName string `json:"typeName,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	Guid string `json:"guid,omitempty"`
	HomeId string `json:"homeId,omitempty"`
	IsProxy bool `json:"isProxy,omitempty"`
	IsIncomplete bool `json:"isIncomplete,omitempty"`
	ProvenanceType int32 `json:"provenanceType,omitempty"`
	Status string `json:"status,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	UpdatedBy string `json:"updatedBy,omitempty"`
	CreateTime int64 `json:"createTime,omitempty"`
	UpdateTime int64 `json:"updateTime,omitempty"`
	Version int64 `json:"version,omitempty"`
	RelationshipAttributes map[string]interface{} `json:"relationshipAttributes,omitempty"`
	Classifications []AtlasClassification `json:"classifications,omitempty"`
	Meanings []AtlasTermAssignmentHeader `json:"meanings,omitempty"`
	CustomAttributes map[string]string `json:"customAttributes,omitempty"`
	BusinessAttributes map[string]map[string]interface{} `json:"businessAttributes,omitempty"`
	Labels []string `json:"labels,omitempty"`
	PendingTasks []string `json:"pendingTasks,omitempty"`
	Proxy bool `json:"proxy,omitempty"`
}
