/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// CompatibilityCheckResponse struct for CompatibilityCheckResponse
type CompatibilityCheckResponse struct {
	IsCompatible bool `json:"is_compatible,omitempty"`
	Messages []string `json:"messages,omitempty"`
}
