/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schema-registry

type SchemaString struct {
	// Schema string identified by the ID
	Schema string `json:"schema,omitempty"`
}
