/*
Confluent Schema Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schemaregistry

import (
	"encoding/json"
)

import (
	"reflect"
)

// RegisterSchemaResponse Schema register response
type RegisterSchemaResponse struct {
	// Globally unique identifier of the schema
	Id *int32 `json:"id,omitempty"`
	// Version number
	Version *int32 `json:"version,omitempty"`
	// Globally unique identifier of the schema
	Guid *string `json:"guid,omitempty"`
	// Schema type
	SchemaType *string `json:"schemaType,omitempty"`
	// References to other schemas
	References *[]SchemaReference `json:"references,omitempty"`
	Metadata NullableMetadata `json:"metadata,omitempty"`
	RuleSet NullableRuleSet `json:"ruleSet,omitempty"`
	// Schema definition string
	Schema *string `json:"schema,omitempty"`
	// Timestamp when the schema was created
	Ts *int64 `json:"ts,omitempty"`
	// Whether the schema has been deleted
	Deleted *bool `json:"deleted,omitempty"`
}

// NewRegisterSchemaResponse instantiates a new RegisterSchemaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterSchemaResponse() *RegisterSchemaResponse {
	this := RegisterSchemaResponse{}
	return &this
}

// NewRegisterSchemaResponseWithDefaults instantiates a new RegisterSchemaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterSchemaResponseWithDefaults() *RegisterSchemaResponse {
	this := RegisterSchemaResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *RegisterSchemaResponse) SetId(v int32) {
	o.Id = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetVersion() int32 {
	if o == nil || o.Version == nil {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetVersionOk() (*int32, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *RegisterSchemaResponse) SetVersion(v int32) {
	o.Version = &v
}

// GetGuid returns the Guid field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetGuid() string {
	if o == nil || o.Guid == nil {
		var ret string
		return ret
	}
	return *o.Guid
}

// GetGuidOk returns a tuple with the Guid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetGuidOk() (*string, bool) {
	if o == nil || o.Guid == nil {
		return nil, false
	}
	return o.Guid, true
}

// HasGuid returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasGuid() bool {
	if o != nil && o.Guid != nil {
		return true
	}

	return false
}

// SetGuid gets a reference to the given string and assigns it to the Guid field.
func (o *RegisterSchemaResponse) SetGuid(v string) {
	o.Guid = &v
}

// GetSchemaType returns the SchemaType field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetSchemaType() string {
	if o == nil || o.SchemaType == nil {
		var ret string
		return ret
	}
	return *o.SchemaType
}

// GetSchemaTypeOk returns a tuple with the SchemaType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetSchemaTypeOk() (*string, bool) {
	if o == nil || o.SchemaType == nil {
		return nil, false
	}
	return o.SchemaType, true
}

// HasSchemaType returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasSchemaType() bool {
	if o != nil && o.SchemaType != nil {
		return true
	}

	return false
}

// SetSchemaType gets a reference to the given string and assigns it to the SchemaType field.
func (o *RegisterSchemaResponse) SetSchemaType(v string) {
	o.SchemaType = &v
}

// GetReferences returns the References field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetReferences() []SchemaReference {
	if o == nil || o.References == nil {
		var ret []SchemaReference
		return ret
	}
	return *o.References
}

// GetReferencesOk returns a tuple with the References field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetReferencesOk() (*[]SchemaReference, bool) {
	if o == nil || o.References == nil {
		return nil, false
	}
	return o.References, true
}

// HasReferences returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasReferences() bool {
	if o != nil && o.References != nil {
		return true
	}

	return false
}

// SetReferences gets a reference to the given []SchemaReference and assigns it to the References field.
func (o *RegisterSchemaResponse) SetReferences(v []SchemaReference) {
	o.References = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegisterSchemaResponse) GetMetadata() Metadata {
	if o == nil || o.Metadata.Get() == nil {
		var ret Metadata
		return ret
	}
	return *o.Metadata.Get()
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegisterSchemaResponse) GetMetadataOk() (*Metadata, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Metadata.Get(), o.Metadata.IsSet()
}

// HasMetadata returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasMetadata() bool {
	if o != nil && o.Metadata.IsSet() {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given NullableMetadata and assigns it to the Metadata field.
func (o *RegisterSchemaResponse) SetMetadata(v Metadata) {
	o.Metadata.Set(&v)
}
// SetMetadataNil sets the value for Metadata to be an explicit nil
func (o *RegisterSchemaResponse) SetMetadataNil() {
	o.Metadata.Set(nil)
}

// UnsetMetadata ensures that no value is present for Metadata, not even an explicit nil
func (o *RegisterSchemaResponse) UnsetMetadata() {
	o.Metadata.Unset()
}

// GetRuleSet returns the RuleSet field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RegisterSchemaResponse) GetRuleSet() RuleSet {
	if o == nil || o.RuleSet.Get() == nil {
		var ret RuleSet
		return ret
	}
	return *o.RuleSet.Get()
}

// GetRuleSetOk returns a tuple with the RuleSet field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RegisterSchemaResponse) GetRuleSetOk() (*RuleSet, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RuleSet.Get(), o.RuleSet.IsSet()
}

// HasRuleSet returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasRuleSet() bool {
	if o != nil && o.RuleSet.IsSet() {
		return true
	}

	return false
}

// SetRuleSet gets a reference to the given NullableRuleSet and assigns it to the RuleSet field.
func (o *RegisterSchemaResponse) SetRuleSet(v RuleSet) {
	o.RuleSet.Set(&v)
}
// SetRuleSetNil sets the value for RuleSet to be an explicit nil
func (o *RegisterSchemaResponse) SetRuleSetNil() {
	o.RuleSet.Set(nil)
}

// UnsetRuleSet ensures that no value is present for RuleSet, not even an explicit nil
func (o *RegisterSchemaResponse) UnsetRuleSet() {
	o.RuleSet.Unset()
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetSchema() string {
	if o == nil || o.Schema == nil {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetSchemaOk() (*string, bool) {
	if o == nil || o.Schema == nil {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasSchema() bool {
	if o != nil && o.Schema != nil {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *RegisterSchemaResponse) SetSchema(v string) {
	o.Schema = &v
}

// GetTs returns the Ts field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetTs() int64 {
	if o == nil || o.Ts == nil {
		var ret int64
		return ret
	}
	return *o.Ts
}

// GetTsOk returns a tuple with the Ts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetTsOk() (*int64, bool) {
	if o == nil || o.Ts == nil {
		return nil, false
	}
	return o.Ts, true
}

// HasTs returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasTs() bool {
	if o != nil && o.Ts != nil {
		return true
	}

	return false
}

// SetTs gets a reference to the given int64 and assigns it to the Ts field.
func (o *RegisterSchemaResponse) SetTs(v int64) {
	o.Ts = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetDeleted() bool {
	if o == nil || o.Deleted == nil {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetDeletedOk() (*bool, bool) {
	if o == nil || o.Deleted == nil {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasDeleted() bool {
	if o != nil && o.Deleted != nil {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *RegisterSchemaResponse) SetDeleted(v bool) {
	o.Deleted = &v
}

// Redact resets all sensitive fields to their zero value.
func (o *RegisterSchemaResponse) Redact() {
    o.recurseRedact(o.Id)
    o.recurseRedact(o.Version)
    o.recurseRedact(o.Guid)
    o.recurseRedact(o.SchemaType)
    o.recurseRedact(o.References)
    o.recurseRedact(o.Metadata)
    o.recurseRedact(o.RuleSet)
    o.recurseRedact(o.Schema)
    o.recurseRedact(o.Ts)
    o.recurseRedact(o.Deleted)
}

func (o *RegisterSchemaResponse) recurseRedact(v interface{}) {
    type redactor interface {
        Redact()
    }
    if r, ok := v.(redactor); ok {
        r.Redact()
    } else {
        val := reflect.ValueOf(v)
        if val.Kind() == reflect.Ptr {
            val = val.Elem()
        }
        switch val.Kind() {
        case reflect.Slice, reflect.Array:
            for i := 0; i < val.Len(); i++ {
                // support data types declared without pointers
                o.recurseRedact(val.Index(i).Interface())
                // ... and data types that were declared without but need pointers (for Redact)
                if val.Index(i).CanAddr() {
                    o.recurseRedact(val.Index(i).Addr().Interface())
                }
            }
        }
    }
}

func (o RegisterSchemaResponse) zeroField(v interface{}) {
    p := reflect.ValueOf(v).Elem()
    p.Set(reflect.Zero(p.Type()))
}

func (o RegisterSchemaResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.Guid != nil {
		toSerialize["guid"] = o.Guid
	}
	if o.SchemaType != nil {
		toSerialize["schemaType"] = o.SchemaType
	}
	if o.References != nil {
		toSerialize["references"] = o.References
	}
	if o.Metadata.IsSet() {
		toSerialize["metadata"] = o.Metadata.Get()
	}
	if o.RuleSet.IsSet() {
		toSerialize["ruleSet"] = o.RuleSet.Get()
	}
	if o.Schema != nil {
		toSerialize["schema"] = o.Schema
	}
	if o.Ts != nil {
		toSerialize["ts"] = o.Ts
	}
	if o.Deleted != nil {
		toSerialize["deleted"] = o.Deleted
	}
	return json.Marshal(toSerialize)
}

type NullableRegisterSchemaResponse struct {
	value *RegisterSchemaResponse
	isSet bool
}

func (v NullableRegisterSchemaResponse) Get() *RegisterSchemaResponse {
	return v.value
}

func (v *NullableRegisterSchemaResponse) Set(val *RegisterSchemaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterSchemaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterSchemaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterSchemaResponse(val *RegisterSchemaResponse) *NullableRegisterSchemaResponse {
	return &NullableRegisterSchemaResponse{value: val, isSet: true}
}

func (v NullableRegisterSchemaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterSchemaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


