/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// RegisterSchemaRequest struct for RegisterSchemaRequest
type RegisterSchemaRequest struct {
	Version int32 `json:"version,omitempty"`
	Id int32 `json:"id,omitempty"`
	SchemaType string `json:"schemaType,omitempty"`
	References []SchemaReference `json:"references,omitempty"`
	Schema string `json:"schema,omitempty"`
}
