/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
import (
	"time"
)
// TagDef struct for TagDef
type TagDef struct {
	Category string `json:"category,omitempty"`
	Guid string `json:"guid,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	UpdatedBy string `json:"updatedBy,omitempty"`
	CreateTime time.Time `json:"createTime,omitempty"`
	UpdateTime time.Time `json:"updateTime,omitempty"`
	Version int64 `json:"version,omitempty"`
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	TypeVersion string `json:"typeVersion,omitempty"`
	ServiceType string `json:"serviceType,omitempty"`
	Options map[string]string `json:"options,omitempty"`
	AttributeDefs []AtlasAttributeDef `json:"attributeDefs,omitempty"`
	SuperTypes []string `json:"superTypes,omitempty"`
	EntityTypes []string `json:"entityTypes,omitempty"`
	SubTypes []string `json:"subTypes,omitempty"`
}
