/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// SchemaReference struct for SchemaReference
type SchemaReference struct {
	Name string `json:"name,omitempty"`
	Subject string `json:"subject,omitempty"`
	Version int32 `json:"version,omitempty"`
}
