/*
Confluent Schema Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schemaregistry

import (
	"encoding/json"
)

// BusinessMetadataResponse struct for BusinessMetadataResponse
type BusinessMetadataResponse struct {
	TypeName *string `json:"typeName,omitempty"`
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	EntityType *string `json:"entityType,omitempty"`
	EntityName *string `json:"entityName,omitempty"`
	Error *ErrorMessage `json:"error,omitempty"`
}

// NewBusinessMetadataResponse instantiates a new BusinessMetadataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBusinessMetadataResponse() *BusinessMetadataResponse {
	this := BusinessMetadataResponse{}
	return &this
}

// NewBusinessMetadataResponseWithDefaults instantiates a new BusinessMetadataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBusinessMetadataResponseWithDefaults() *BusinessMetadataResponse {
	this := BusinessMetadataResponse{}
	return &this
}

// GetTypeName returns the TypeName field value if set, zero value otherwise.
func (o *BusinessMetadataResponse) GetTypeName() string {
	if o == nil || o.TypeName == nil {
		var ret string
		return ret
	}
	return *o.TypeName
}

// GetTypeNameOk returns a tuple with the TypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessMetadataResponse) GetTypeNameOk() (*string, bool) {
	if o == nil || o.TypeName == nil {
		return nil, false
	}
	return o.TypeName, true
}

// HasTypeName returns a boolean if a field has been set.
func (o *BusinessMetadataResponse) HasTypeName() bool {
	if o != nil && o.TypeName != nil {
		return true
	}

	return false
}

// SetTypeName gets a reference to the given string and assigns it to the TypeName field.
func (o *BusinessMetadataResponse) SetTypeName(v string) {
	o.TypeName = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *BusinessMetadataResponse) GetAttributes() map[string]interface{} {
	if o == nil || o.Attributes == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessMetadataResponse) GetAttributesOk() (*map[string]interface{}, bool) {
	if o == nil || o.Attributes == nil {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *BusinessMetadataResponse) HasAttributes() bool {
	if o != nil && o.Attributes != nil {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given map[string]interface{} and assigns it to the Attributes field.
func (o *BusinessMetadataResponse) SetAttributes(v map[string]interface{}) {
	o.Attributes = &v
}

// GetEntityType returns the EntityType field value if set, zero value otherwise.
func (o *BusinessMetadataResponse) GetEntityType() string {
	if o == nil || o.EntityType == nil {
		var ret string
		return ret
	}
	return *o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessMetadataResponse) GetEntityTypeOk() (*string, bool) {
	if o == nil || o.EntityType == nil {
		return nil, false
	}
	return o.EntityType, true
}

// HasEntityType returns a boolean if a field has been set.
func (o *BusinessMetadataResponse) HasEntityType() bool {
	if o != nil && o.EntityType != nil {
		return true
	}

	return false
}

// SetEntityType gets a reference to the given string and assigns it to the EntityType field.
func (o *BusinessMetadataResponse) SetEntityType(v string) {
	o.EntityType = &v
}

// GetEntityName returns the EntityName field value if set, zero value otherwise.
func (o *BusinessMetadataResponse) GetEntityName() string {
	if o == nil || o.EntityName == nil {
		var ret string
		return ret
	}
	return *o.EntityName
}

// GetEntityNameOk returns a tuple with the EntityName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessMetadataResponse) GetEntityNameOk() (*string, bool) {
	if o == nil || o.EntityName == nil {
		return nil, false
	}
	return o.EntityName, true
}

// HasEntityName returns a boolean if a field has been set.
func (o *BusinessMetadataResponse) HasEntityName() bool {
	if o != nil && o.EntityName != nil {
		return true
	}

	return false
}

// SetEntityName gets a reference to the given string and assigns it to the EntityName field.
func (o *BusinessMetadataResponse) SetEntityName(v string) {
	o.EntityName = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *BusinessMetadataResponse) GetError() ErrorMessage {
	if o == nil || o.Error == nil {
		var ret ErrorMessage
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BusinessMetadataResponse) GetErrorOk() (*ErrorMessage, bool) {
	if o == nil || o.Error == nil {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *BusinessMetadataResponse) HasError() bool {
	if o != nil && o.Error != nil {
		return true
	}

	return false
}

// SetError gets a reference to the given ErrorMessage and assigns it to the Error field.
func (o *BusinessMetadataResponse) SetError(v ErrorMessage) {
	o.Error = &v
}

func (o BusinessMetadataResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TypeName != nil {
		toSerialize["typeName"] = o.TypeName
	}
	if o.Attributes != nil {
		toSerialize["attributes"] = o.Attributes
	}
	if o.EntityType != nil {
		toSerialize["entityType"] = o.EntityType
	}
	if o.EntityName != nil {
		toSerialize["entityName"] = o.EntityName
	}
	if o.Error != nil {
		toSerialize["error"] = o.Error
	}
	return json.Marshal(toSerialize)
}

type NullableBusinessMetadataResponse struct {
	value *BusinessMetadataResponse
	isSet bool
}

func (v NullableBusinessMetadataResponse) Get() *BusinessMetadataResponse {
	return v.value
}

func (v *NullableBusinessMetadataResponse) Set(val *BusinessMetadataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBusinessMetadataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBusinessMetadataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBusinessMetadataResponse(val *BusinessMetadataResponse) *NullableBusinessMetadataResponse {
	return &NullableBusinessMetadataResponse{value: val, isSet: true}
}

func (v NullableBusinessMetadataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBusinessMetadataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


