/*
Confluent Schema Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schemaregistry

import (
	"encoding/json"
)

// AtlasConstraintDef struct for AtlasConstraintDef
type AtlasConstraintDef struct {
	Type *string `json:"type,omitempty"`
	Params *map[string]map[string]interface{} `json:"params,omitempty"`
}

// NewAtlasConstraintDef instantiates a new AtlasConstraintDef object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAtlasConstraintDef() *AtlasConstraintDef {
	this := AtlasConstraintDef{}
	return &this
}

// NewAtlasConstraintDefWithDefaults instantiates a new AtlasConstraintDef object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAtlasConstraintDefWithDefaults() *AtlasConstraintDef {
	this := AtlasConstraintDef{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *AtlasConstraintDef) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AtlasConstraintDef) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *AtlasConstraintDef) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *AtlasConstraintDef) SetType(v string) {
	o.Type = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *AtlasConstraintDef) GetParams() map[string]map[string]interface{} {
	if o == nil || o.Params == nil {
		var ret map[string]map[string]interface{}
		return ret
	}
	return *o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AtlasConstraintDef) GetParamsOk() (*map[string]map[string]interface{}, bool) {
	if o == nil || o.Params == nil {
		return nil, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *AtlasConstraintDef) HasParams() bool {
	if o != nil && o.Params != nil {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]map[string]interface{} and assigns it to the Params field.
func (o *AtlasConstraintDef) SetParams(v map[string]map[string]interface{}) {
	o.Params = &v
}

func (o AtlasConstraintDef) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Params != nil {
		toSerialize["params"] = o.Params
	}
	return json.Marshal(toSerialize)
}

type NullableAtlasConstraintDef struct {
	value *AtlasConstraintDef
	isSet bool
}

func (v NullableAtlasConstraintDef) Get() *AtlasConstraintDef {
	return v.value
}

func (v *NullableAtlasConstraintDef) Set(val *AtlasConstraintDef) {
	v.value = val
	v.isSet = true
}

func (v NullableAtlasConstraintDef) IsSet() bool {
	return v.isSet
}

func (v *NullableAtlasConstraintDef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAtlasConstraintDef(val *AtlasConstraintDef) *NullableAtlasConstraintDef {
	return &NullableAtlasConstraintDef{value: val, isSet: true}
}

func (v NullableAtlasConstraintDef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAtlasConstraintDef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


