/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// Metadata User-defined metadata
type Metadata struct {
	Tags map[string][]string `json:"tags,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
	Sensitive []string `json:"sensitive,omitempty"`
}
