/*
Confluent Schema Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schemaregistry

import (
	"encoding/json"
)

// SearchParams struct for SearchParams
type SearchParams struct {
	IncludeDeleted *bool `json:"includeDeleted,omitempty"`
	Limit *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

// NewSearchParams instantiates a new SearchParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchParams() *SearchParams {
	this := SearchParams{}
	return &this
}

// NewSearchParamsWithDefaults instantiates a new SearchParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchParamsWithDefaults() *SearchParams {
	this := SearchParams{}
	return &this
}

// GetIncludeDeleted returns the IncludeDeleted field value if set, zero value otherwise.
func (o *SearchParams) GetIncludeDeleted() bool {
	if o == nil || o.IncludeDeleted == nil {
		var ret bool
		return ret
	}
	return *o.IncludeDeleted
}

// GetIncludeDeletedOk returns a tuple with the IncludeDeleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchParams) GetIncludeDeletedOk() (*bool, bool) {
	if o == nil || o.IncludeDeleted == nil {
		return nil, false
	}
	return o.IncludeDeleted, true
}

// HasIncludeDeleted returns a boolean if a field has been set.
func (o *SearchParams) HasIncludeDeleted() bool {
	if o != nil && o.IncludeDeleted != nil {
		return true
	}

	return false
}

// SetIncludeDeleted gets a reference to the given bool and assigns it to the IncludeDeleted field.
func (o *SearchParams) SetIncludeDeleted(v bool) {
	o.IncludeDeleted = &v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *SearchParams) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchParams) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *SearchParams) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *SearchParams) SetLimit(v int32) {
	o.Limit = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *SearchParams) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchParams) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *SearchParams) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *SearchParams) SetOffset(v int32) {
	o.Offset = &v
}

func (o SearchParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.IncludeDeleted != nil {
		toSerialize["includeDeleted"] = o.IncludeDeleted
	}
	if o.Limit != nil {
		toSerialize["limit"] = o.Limit
	}
	if o.Offset != nil {
		toSerialize["offset"] = o.Offset
	}
	return json.Marshal(toSerialize)
}

type NullableSearchParams struct {
	value *SearchParams
	isSet bool
}

func (v NullableSearchParams) Get() *SearchParams {
	return v.value
}

func (v *NullableSearchParams) Set(val *SearchParams) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchParams) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchParams(val *SearchParams) *NullableSearchParams {
	return &NullableSearchParams{value: val, isSet: true}
}

func (v NullableSearchParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


