/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// Config struct for Config
type Config struct {
	// Compatability Level
	CompatibilityLevel string `json:"compatibilityLevel,omitempty"`
}
