/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// BusinessMetadataResponse struct for BusinessMetadataResponse
type BusinessMetadataResponse struct {
	TypeName string `json:"typeName,omitempty"`
	Attributes map[string]interface{} `json:"attributes,omitempty"`
	EntityType string `json:"entityType,omitempty"`
	EntityName string `json:"entityName,omitempty"`
	Error ErrorMessage `json:"error,omitempty"`
}
