/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// ErrorMessage struct for ErrorMessage
type ErrorMessage struct {
	ErrorCode int32 `json:"error_code,omitempty"`
	Message string `json:"message,omitempty"`
}
