/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateExporterResponse struct for CreateExporterResponse
type CreateExporterResponse struct {
	Name *string `json:"name,omitempty"`
}

// NewCreateExporterResponse instantiates a new CreateExporterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateExporterResponse() *CreateExporterResponse {
	this := CreateExporterResponse{}
	return &this
}

// NewCreateExporterResponseWithDefaults instantiates a new CreateExporterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateExporterResponseWithDefaults() *CreateExporterResponse {
	this := CreateExporterResponse{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateExporterResponse) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateExporterResponse) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateExporterResponse) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateExporterResponse) SetName(v string) {
	o.Name = &v
}

func (o CreateExporterResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateExporterResponse struct {
	value *CreateExporterResponse
	isSet bool
}

func (v NullableCreateExporterResponse) Get() *CreateExporterResponse {
	return v.value
}

func (v *NullableCreateExporterResponse) Set(val *CreateExporterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateExporterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateExporterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateExporterResponse(val *CreateExporterResponse) *NullableCreateExporterResponse {
	return &NullableCreateExporterResponse{value: val, isSet: true}
}

func (v NullableCreateExporterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateExporterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


