/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// SchemaString struct for SchemaString
type SchemaString struct {
	// Schema type
	SchemaType string `json:"schemaType,omitempty"`
	// Schema string identified by the ID
	Schema string `json:"schema,omitempty"`
	// Schema references
	References []SchemaReference `json:"references,omitempty"`
	// Maximum ID
	MaxId int32 `json:"maxId,omitempty"`
}
