/*
Confluent Schema Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schemaregistry

import (
	"encoding/json"
)

// SchemaEntity struct for SchemaEntity
type SchemaEntity struct {
	EntityPath *string `json:"entityPath,omitempty"`
	EntityType *string `json:"entityType,omitempty"`
}

// NewSchemaEntity instantiates a new SchemaEntity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaEntity() *SchemaEntity {
	this := SchemaEntity{}
	return &this
}

// NewSchemaEntityWithDefaults instantiates a new SchemaEntity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaEntityWithDefaults() *SchemaEntity {
	this := SchemaEntity{}
	return &this
}

// GetEntityPath returns the EntityPath field value if set, zero value otherwise.
func (o *SchemaEntity) GetEntityPath() string {
	if o == nil || o.EntityPath == nil {
		var ret string
		return ret
	}
	return *o.EntityPath
}

// GetEntityPathOk returns a tuple with the EntityPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaEntity) GetEntityPathOk() (*string, bool) {
	if o == nil || o.EntityPath == nil {
		return nil, false
	}
	return o.EntityPath, true
}

// HasEntityPath returns a boolean if a field has been set.
func (o *SchemaEntity) HasEntityPath() bool {
	if o != nil && o.EntityPath != nil {
		return true
	}

	return false
}

// SetEntityPath gets a reference to the given string and assigns it to the EntityPath field.
func (o *SchemaEntity) SetEntityPath(v string) {
	o.EntityPath = &v
}

// GetEntityType returns the EntityType field value if set, zero value otherwise.
func (o *SchemaEntity) GetEntityType() string {
	if o == nil || o.EntityType == nil {
		var ret string
		return ret
	}
	return *o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaEntity) GetEntityTypeOk() (*string, bool) {
	if o == nil || o.EntityType == nil {
		return nil, false
	}
	return o.EntityType, true
}

// HasEntityType returns a boolean if a field has been set.
func (o *SchemaEntity) HasEntityType() bool {
	if o != nil && o.EntityType != nil {
		return true
	}

	return false
}

// SetEntityType gets a reference to the given string and assigns it to the EntityType field.
func (o *SchemaEntity) SetEntityType(v string) {
	o.EntityType = &v
}

func (o SchemaEntity) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.EntityPath != nil {
		toSerialize["entityPath"] = o.EntityPath
	}
	if o.EntityType != nil {
		toSerialize["entityType"] = o.EntityType
	}
	return json.Marshal(toSerialize)
}

type NullableSchemaEntity struct {
	value *SchemaEntity
	isSet bool
}

func (v NullableSchemaEntity) Get() *SchemaEntity {
	return v.value
}

func (v *NullableSchemaEntity) Set(val *SchemaEntity) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaEntity) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaEntity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaEntity(val *SchemaEntity) *NullableSchemaEntity {
	return &NullableSchemaEntity{value: val, isSet: true}
}

func (v NullableSchemaEntity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaEntity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


