/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// AtlasEntityHeader struct for AtlasEntityHeader
type AtlasEntityHeader struct {
	TypeName string `json:"typeName,omitempty"`
	Attributes map[string]map[string]interface{} `json:"attributes,omitempty"`
	Guid string `json:"guid,omitempty"`
	Status string `json:"status,omitempty"`
	DisplayText string `json:"displayText,omitempty"`
	ClassificationNames []string `json:"classificationNames,omitempty"`
	Classifications []AtlasClassification `json:"classifications,omitempty"`
	MeaningNames []string `json:"meaningNames,omitempty"`
	Meanings []AtlasTermAssignmentHeader `json:"meanings,omitempty"`
	IsIncomplete bool `json:"isIncomplete,omitempty"`
	Labels []string `json:"labels,omitempty"`
}
