/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// AtlasTermAssignmentHeader struct for AtlasTermAssignmentHeader
type AtlasTermAssignmentHeader struct {
	TermGuid string `json:"termGuid,omitempty"`
	RelationGuid string `json:"relationGuid,omitempty"`
	Description string `json:"description,omitempty"`
	DisplayText string `json:"displayText,omitempty"`
	Expression string `json:"expression,omitempty"`
	CreatedBy string `json:"createdBy,omitempty"`
	Steward string `json:"steward,omitempty"`
	Source string `json:"source,omitempty"`
	Confidence int32 `json:"confidence,omitempty"`
	Status string `json:"status,omitempty"`
}
