/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry

type ServerClusterId struct {
	Scope map[string]map[string]interface{} `json:"scope,omitempty"`
	Id string `json:"id,omitempty"`
}
