/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// TimeBoundary struct for TimeBoundary
type TimeBoundary struct {
	StartTime string `json:"startTime,omitempty"`
	EndTime string `json:"endTime,omitempty"`
	TimeZone string `json:"timeZone,omitempty"`
}
