/*
 * Confluent Schema Registry
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package schemaregistry
// TagResponse struct for TagResponse
type TagResponse struct {
	TypeName string `json:"typeName,omitempty"`
	Attributes map[string]map[string]interface{} `json:"attributes,omitempty"`
	EntityGuid string `json:"entityGuid,omitempty"`
	EntityStatus string `json:"entityStatus,omitempty"`
	Propagate bool `json:"propagate,omitempty"`
	ValidityPeriods []TimeBoundary `json:"validityPeriods,omitempty"`
	RemovePropagationsOnEntityDelete bool `json:"removePropagationsOnEntityDelete,omitempty"`
	EntityType string `json:"entityType,omitempty"`
	EntityName string `json:"entityName,omitempty"`
	Error ErrorMessage `json:"error,omitempty"`
}
