/*
Confluent Schema Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schemaregistry

import (
	"encoding/json"
)

// RegisterSchemaResponse Schema register response
type RegisterSchemaResponse struct {
	// Globally unique identifier of the schema
	Id *int32 `json:"id,omitempty"`
}

// NewRegisterSchemaResponse instantiates a new RegisterSchemaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterSchemaResponse() *RegisterSchemaResponse {
	this := RegisterSchemaResponse{}
	return &this
}

// NewRegisterSchemaResponseWithDefaults instantiates a new RegisterSchemaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterSchemaResponseWithDefaults() *RegisterSchemaResponse {
	this := RegisterSchemaResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RegisterSchemaResponse) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterSchemaResponse) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RegisterSchemaResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *RegisterSchemaResponse) SetId(v int32) {
	o.Id = &v
}

func (o RegisterSchemaResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableRegisterSchemaResponse struct {
	value *RegisterSchemaResponse
	isSet bool
}

func (v NullableRegisterSchemaResponse) Get() *RegisterSchemaResponse {
	return v.value
}

func (v *NullableRegisterSchemaResponse) Set(val *RegisterSchemaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterSchemaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterSchemaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterSchemaResponse(val *RegisterSchemaResponse) *NullableRegisterSchemaResponse {
	return &NullableRegisterSchemaResponse{value: val, isSet: true}
}

func (v NullableRegisterSchemaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterSchemaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


