/*
Confluent Schema Registry

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package schemaregistry

import (
	"encoding/json"
)

// SchemaTags struct for SchemaTags
type SchemaTags struct {
	SchemaEntity *SchemaEntity `json:"schemaEntity,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
}

// NewSchemaTags instantiates a new SchemaTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSchemaTags() *SchemaTags {
	this := SchemaTags{}
	return &this
}

// NewSchemaTagsWithDefaults instantiates a new SchemaTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSchemaTagsWithDefaults() *SchemaTags {
	this := SchemaTags{}
	return &this
}

// GetSchemaEntity returns the SchemaEntity field value if set, zero value otherwise.
func (o *SchemaTags) GetSchemaEntity() SchemaEntity {
	if o == nil || o.SchemaEntity == nil {
		var ret SchemaEntity
		return ret
	}
	return *o.SchemaEntity
}

// GetSchemaEntityOk returns a tuple with the SchemaEntity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaTags) GetSchemaEntityOk() (*SchemaEntity, bool) {
	if o == nil || o.SchemaEntity == nil {
		return nil, false
	}
	return o.SchemaEntity, true
}

// HasSchemaEntity returns a boolean if a field has been set.
func (o *SchemaTags) HasSchemaEntity() bool {
	if o != nil && o.SchemaEntity != nil {
		return true
	}

	return false
}

// SetSchemaEntity gets a reference to the given SchemaEntity and assigns it to the SchemaEntity field.
func (o *SchemaTags) SetSchemaEntity(v SchemaEntity) {
	o.SchemaEntity = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *SchemaTags) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SchemaTags) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SchemaTags) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SchemaTags) SetTags(v []string) {
	o.Tags = &v
}

func (o SchemaTags) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SchemaEntity != nil {
		toSerialize["schemaEntity"] = o.SchemaEntity
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	return json.Marshal(toSerialize)
}

type NullableSchemaTags struct {
	value *SchemaTags
	isSet bool
}

func (v NullableSchemaTags) Get() *SchemaTags {
	return v.value
}

func (v *NullableSchemaTags) Set(val *SchemaTags) {
	v.value = val
	v.isSet = true
}

func (v NullableSchemaTags) IsSet() bool {
	return v.isSet
}

func (v *NullableSchemaTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSchemaTags(val *SchemaTags) *NullableSchemaTags {
	return &NullableSchemaTags{value: val, isSet: true}
}

func (v NullableSchemaTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSchemaTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


